apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-mlops-automation-pipelines-local
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
